Changed Things
williamrockowl/webdevcourse pull request #9
Opened 2021-02-24 11:01 UTC by williamrockowl

Changed the css file name to something more simple, as well as I added more content to the dropdown nav bar.

2021-02-24 23:02 UTC, billythakidd04 requested changes
Few small changes but its getting there

2021-02-24 23:02 UTC, billythakidd04 commented on William_Saulon.htm
> +        <a href="https://sites.google.com/site/buffalolittlelamb8/" target=" blank">- CLICK HERE TO GO TO MY FAVORITE RESTAURANT IN BUFFALO, NY</a> </p>
i think you meant `target="_blank"`

2021-02-24 23:02 UTC, billythakidd04 commented on William_Saulon.htm
> +<hr>
close tag

2021-02-24 23:02 UTC, billythakidd04 commented on cssFolder/myStyles.css
> +}
you have `inline-block` in the section above, why `block` here?

2021-02-26 01:24 UTC, williamrockowl commented on William_Saulon.htm
> +<hr>
using the hr tag as a break, closing it makes it dissapear.

2021-02-26 01:24 UTC, williamrockowl commented on William_Saulon.htm
> +        <hr>
using the hr tag as a break, closing it makes it dissapear.

2021-02-26 02:25 UTC, billythakidd04 requested changes
Still missing some changes, especially the image paths. If the `<hr/>` tag gives you trouble, let me know I'll help.

2021-02-26 02:25 UTC, billythakidd04 commented on William_Saulon.htm
> +        <hr>
That's not how that works. You're doing some thing else wrong then. Close the tag, If it doesn't work send me a screenshot

2021-02-26 02:25 UTC, billythakidd04 commented on William_Saulon.htm
> +            <img src="Image\IMG_0908.jpg" alt="Hiking Trip" style="width:300px;height:400px;">
This still needs to be fixed

2021-02-27 20:13 UTC, billythakidd04 approved these changes

2021-02-27 20:19 UTC, merged